// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilSubmitNameChangeRequest is returned when the SubmitNameChangeRequest is nil.
	ErrNilSubmitNameChangeRequest = errors.New("input SubmitNameChangeRequest is nil")

	// ErrSubmitNameChangeRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrSubmitNameChangeRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "SubmitNameChangeRequest.RequestID", Type: "required"}

	// ErrSubmitNameChangeRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrSubmitNameChangeRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "SubmitNameChangeRequest.RequestID", Type: "uuid"}

	// ErrSubmitNameChangeRequestUploadedDocumentsMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrSubmitNameChangeRequestUploadedDocumentsMinItemsValidation = govaliderrors.ValidationError{Reason: "field UploadedDocuments must have a minimum of 1 items", Path: "SubmitNameChangeRequest.UploadedDocuments", Type: "minitems"}

	// ErrSubmitNameChangeRequestUploadedDocumentsRequiredValidation is returned when the UploadedDocuments is required but not provided.
	ErrSubmitNameChangeRequestUploadedDocumentsRequiredValidation = govaliderrors.ValidationError{Reason: "field UploadedDocuments is required", Path: "SubmitNameChangeRequest.UploadedDocuments", Type: "required"}

	// ErrSubmitNameChangeRequestDeclarationRequiredValidation is returned when the Declaration is required but not provided.
	ErrSubmitNameChangeRequestDeclarationRequiredValidation = govaliderrors.ValidationError{Reason: "field Declaration is required", Path: "SubmitNameChangeRequest.Declaration", Type: "required"}

	// ErrSubmitNameChangeRequestSubmittedByRequiredValidation is returned when the SubmittedBy is required but not provided.
	ErrSubmitNameChangeRequestSubmittedByRequiredValidation = govaliderrors.ValidationError{Reason: "field SubmittedBy is required", Path: "SubmitNameChangeRequest.SubmittedBy", Type: "required"}
)

func ValidateSubmitNameChangeRequest(t *SubmitNameChangeRequest) error {
	if t == nil {
		return ErrNilSubmitNameChangeRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrSubmitNameChangeRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrSubmitNameChangeRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if len(t.UploadedDocuments) < 1 {
		err := ErrSubmitNameChangeRequestUploadedDocumentsMinItemsValidation
		err.Value = t.UploadedDocuments
		errs = append(errs, err)
	}

	if t.UploadedDocuments == nil {
		err := ErrSubmitNameChangeRequestUploadedDocumentsRequiredValidation
		err.Value = t.UploadedDocuments
		errs = append(errs, err)
	}

	if t.Declaration == false {
		err := ErrSubmitNameChangeRequestDeclarationRequiredValidation
		err.Value = t.Declaration
		errs = append(errs, err)
	}

	if t.SubmittedBy == "" {
		err := ErrSubmitNameChangeRequestSubmittedByRequiredValidation
		err.Value = t.SubmittedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SubmitNameChangeRequest)(nil)

func (t *SubmitNameChangeRequest) Validate() error {
	return ValidateSubmitNameChangeRequest(t)
}
