// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilValidatePincodeRequest is returned when the ValidatePincodeRequest is nil.
	ErrNilValidatePincodeRequest = errors.New("input ValidatePincodeRequest is nil")

	// ErrValidatePincodeRequestPincodeLengthValidation is the error returned when the length of the field is not exactly 6.
	ErrValidatePincodeRequestPincodeLengthValidation = govaliderrors.ValidationError{Reason: "field Pincode length must be exactly 6", Path: "ValidatePincodeRequest.Pincode", Type: "length"}

	// ErrValidatePincodeRequestPincodeNumericValidation is the error returned when the field Pincode is not numeric.
	ErrValidatePincodeRequestPincodeNumericValidation = govaliderrors.ValidationError{Reason: "field Pincode must be numeric", Path: "ValidatePincodeRequest.Pincode", Type: "numeric"}

	// ErrValidatePincodeRequestPincodeRequiredValidation is returned when the Pincode is required but not provided.
	ErrValidatePincodeRequestPincodeRequiredValidation = govaliderrors.ValidationError{Reason: "field Pincode is required", Path: "ValidatePincodeRequest.Pincode", Type: "required"}
)

func ValidateValidatePincodeRequest(t *ValidatePincodeRequest) error {
	if t == nil {
		return ErrNilValidatePincodeRequest
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Pincode) != 6 {
		err := ErrValidatePincodeRequestPincodeLengthValidation
		err.Value = t.Pincode
		errs = append(errs, err)
	}

	if !validationhelper.IsNumeric(t.Pincode) {
		err := ErrValidatePincodeRequestPincodeNumericValidation
		err.Value = t.Pincode
		errs = append(errs, err)
	}

	if t.Pincode == "" {
		err := ErrValidatePincodeRequestPincodeRequiredValidation
		err.Value = t.Pincode
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ValidatePincodeRequest)(nil)

func (t *ValidatePincodeRequest) Validate() error {
	return ValidateValidatePincodeRequest(t)
}
