// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilValidateNameFieldsRequest is returned when the ValidateNameFieldsRequest is nil.
	ErrNilValidateNameFieldsRequest = errors.New("input ValidateNameFieldsRequest is nil")
)

func ValidateValidateNameFieldsRequest(t *ValidateNameFieldsRequest) error {
	if t == nil {
		return ErrNilValidateNameFieldsRequest
	}

	var errs govaliderrors.ValidationErrors

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ValidateNameFieldsRequest)(nil)

func (t *ValidateNameFieldsRequest) Validate() error {
	return ValidateValidateNameFieldsRequest(t)
}
