// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilListDocumentTypesRequest is returned when the ListDocumentTypesRequest is nil.
	ErrNilListDocumentTypesRequest = errors.New("input ListDocumentTypesRequest is nil")

	// ErrListDocumentTypesRequestRequestTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrListDocumentTypesRequestRequestTypeOneofValidation = govaliderrors.ValidationError{Reason: "field RequestType must be one of ADDRESS_CHANGE NAME_CHANGE", Path: "ListDocumentTypesRequest.RequestType", Type: "oneof"}

	// ErrListDocumentTypesRequestRequestTypeRequiredValidation is returned when the RequestType is required but not provided.
	ErrListDocumentTypesRequestRequestTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestType is required", Path: "ListDocumentTypesRequest.RequestType", Type: "required"}
)

func ValidateListDocumentTypesRequest(t *ListDocumentTypesRequest) error {
	if t == nil {
		return ErrNilListDocumentTypesRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.RequestType == "ADDRESS_CHANGE" || t.RequestType == "NAME_CHANGE") {
		err := ErrListDocumentTypesRequestRequestTypeOneofValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.RequestType == "" {
		err := ErrListDocumentTypesRequestRequestTypeRequiredValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ListDocumentTypesRequest)(nil)

func (t *ListDocumentTypesRequest) Validate() error {
	return ValidateListDocumentTypesRequest(t)
}
