// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilVerifyNameOTPRequest is returned when the VerifyNameOTPRequest is nil.
	ErrNilVerifyNameOTPRequest = errors.New("input VerifyNameOTPRequest is nil")

	// ErrVerifyNameOTPRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrVerifyNameOTPRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "VerifyNameOTPRequest.RequestID", Type: "required"}

	// ErrVerifyNameOTPRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrVerifyNameOTPRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "VerifyNameOTPRequest.RequestID", Type: "uuid"}

	// ErrVerifyNameOTPRequestOTPCodeLengthValidation is the error returned when the length of the field is not exactly 6.
	ErrVerifyNameOTPRequestOTPCodeLengthValidation = govaliderrors.ValidationError{Reason: "field OTPCode length must be exactly 6", Path: "VerifyNameOTPRequest.OTPCode", Type: "length"}

	// ErrVerifyNameOTPRequestOTPCodeNumericValidation is the error returned when the field OTPCode is not numeric.
	ErrVerifyNameOTPRequestOTPCodeNumericValidation = govaliderrors.ValidationError{Reason: "field OTPCode must be numeric", Path: "VerifyNameOTPRequest.OTPCode", Type: "numeric"}

	// ErrVerifyNameOTPRequestOTPCodeRequiredValidation is returned when the OTPCode is required but not provided.
	ErrVerifyNameOTPRequestOTPCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field OTPCode is required", Path: "VerifyNameOTPRequest.OTPCode", Type: "required"}

	// ErrVerifyNameOTPRequestTxnIDRequiredValidation is returned when the TxnID is required but not provided.
	ErrVerifyNameOTPRequestTxnIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TxnID is required", Path: "VerifyNameOTPRequest.TxnID", Type: "required"}
)

func ValidateVerifyNameOTPRequest(t *VerifyNameOTPRequest) error {
	if t == nil {
		return ErrNilVerifyNameOTPRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrVerifyNameOTPRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrVerifyNameOTPRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.OTPCode) != 6 {
		err := ErrVerifyNameOTPRequestOTPCodeLengthValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if !validationhelper.IsNumeric(t.OTPCode) {
		err := ErrVerifyNameOTPRequestOTPCodeNumericValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if t.OTPCode == "" {
		err := ErrVerifyNameOTPRequestOTPCodeRequiredValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if t.TxnID == "" {
		err := ErrVerifyNameOTPRequestTxnIDRequiredValidation
		err.Value = t.TxnID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*VerifyNameOTPRequest)(nil)

func (t *VerifyNameOTPRequest) Validate() error {
	return ValidateVerifyNameOTPRequest(t)
}
