// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilApproveNameChangeRequest is returned when the ApproveNameChangeRequest is nil.
	ErrNilApproveNameChangeRequest = errors.New("input ApproveNameChangeRequest is nil")

	// ErrApproveNameChangeRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrApproveNameChangeRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "ApproveNameChangeRequest.RequestID", Type: "required"}

	// ErrApproveNameChangeRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrApproveNameChangeRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "ApproveNameChangeRequest.RequestID", Type: "uuid"}

	// ErrApproveNameChangeRequestDecisionOneofValidation is the error returned when the field is not one of the allowed values.
	ErrApproveNameChangeRequestDecisionOneofValidation = govaliderrors.ValidationError{Reason: "field Decision must be one of APPROVE REJECT SEND_BACK", Path: "ApproveNameChangeRequest.Decision", Type: "oneof"}

	// ErrApproveNameChangeRequestDecisionRequiredValidation is returned when the Decision is required but not provided.
	ErrApproveNameChangeRequestDecisionRequiredValidation = govaliderrors.ValidationError{Reason: "field Decision is required", Path: "ApproveNameChangeRequest.Decision", Type: "required"}

	// ErrApproveNameChangeRequestApprovedByRequiredValidation is returned when the ApprovedBy is required but not provided.
	ErrApproveNameChangeRequestApprovedByRequiredValidation = govaliderrors.ValidationError{Reason: "field ApprovedBy is required", Path: "ApproveNameChangeRequest.ApprovedBy", Type: "required"}
)

func ValidateApproveNameChangeRequest(t *ApproveNameChangeRequest) error {
	if t == nil {
		return ErrNilApproveNameChangeRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrApproveNameChangeRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrApproveNameChangeRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !(t.Decision == "APPROVE" || t.Decision == "REJECT" || t.Decision == "SEND_BACK") {
		err := ErrApproveNameChangeRequestDecisionOneofValidation
		err.Value = t.Decision
		errs = append(errs, err)
	}

	if t.Decision == "" {
		err := ErrApproveNameChangeRequestDecisionRequiredValidation
		err.Value = t.Decision
		errs = append(errs, err)
	}

	if t.ApprovedBy == "" {
		err := ErrApproveNameChangeRequestApprovedByRequiredValidation
		err.Value = t.ApprovedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ApproveNameChangeRequest)(nil)

func (t *ApproveNameChangeRequest) Validate() error {
	return ValidateApproveNameChangeRequest(t)
}
