// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilSecureUploadDocumentRequest is returned when the SecureUploadDocumentRequest is nil.
	ErrNilSecureUploadDocumentRequest = errors.New("input SecureUploadDocumentRequest is nil")

	// ErrSecureUploadDocumentRequestTokenRequiredValidation is returned when the Token is required but not provided.
	ErrSecureUploadDocumentRequestTokenRequiredValidation = govaliderrors.ValidationError{Reason: "field Token is required", Path: "SecureUploadDocumentRequest.Token", Type: "required"}

	// ErrSecureUploadDocumentRequestDocumentTypeRequiredValidation is returned when the DocumentType is required but not provided.
	ErrSecureUploadDocumentRequestDocumentTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentType is required", Path: "SecureUploadDocumentRequest.DocumentType", Type: "required"}
)

func ValidateSecureUploadDocumentRequest(t *SecureUploadDocumentRequest) error {
	if t == nil {
		return ErrNilSecureUploadDocumentRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.Token == "" {
		err := ErrSecureUploadDocumentRequestTokenRequiredValidation
		err.Value = t.Token
		errs = append(errs, err)
	}

	if t.DocumentType == "" {
		err := ErrSecureUploadDocumentRequestDocumentTypeRequiredValidation
		err.Value = t.DocumentType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SecureUploadDocumentRequest)(nil)

func (t *SecureUploadDocumentRequest) Validate() error {
	return ValidateSecureUploadDocumentRequest(t)
}
