// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetRequestDetailRequest is returned when the GetRequestDetailRequest is nil.
	ErrNilGetRequestDetailRequest = errors.New("input GetRequestDetailRequest is nil")

	// ErrGetRequestDetailRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrGetRequestDetailRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "GetRequestDetailRequest.RequestID", Type: "required"}

	// ErrGetRequestDetailRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrGetRequestDetailRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "GetRequestDetailRequest.RequestID", Type: "uuid"}
)

func ValidateGetRequestDetailRequest(t *GetRequestDetailRequest) error {
	if t == nil {
		return ErrNilGetRequestDetailRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrGetRequestDetailRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrGetRequestDetailRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetRequestDetailRequest)(nil)

func (t *GetRequestDetailRequest) Validate() error {
	return ValidateGetRequestDetailRequest(t)
}
