// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilVerifyOTPRequest is returned when the VerifyOTPRequest is nil.
	ErrNilVerifyOTPRequest = errors.New("input VerifyOTPRequest is nil")

	// ErrVerifyOTPRequestRequestIDMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrVerifyOTPRequestRequestIDMaxLengthValidation = govaliderrors.ValidationError{Reason: "field RequestID must have a maximum length of 50", Path: "VerifyOTPRequest.RequestID", Type: "maxlength"}

	// ErrVerifyOTPRequestRequestIDMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrVerifyOTPRequestRequestIDMinLengthValidation = govaliderrors.ValidationError{Reason: "field RequestID must have a minimum length of 1", Path: "VerifyOTPRequest.RequestID", Type: "minlength"}

	// ErrVerifyOTPRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrVerifyOTPRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "VerifyOTPRequest.RequestID", Type: "required"}

	// ErrVerifyOTPRequestOTPCodeLengthValidation is the error returned when the length of the field is not exactly 6.
	ErrVerifyOTPRequestOTPCodeLengthValidation = govaliderrors.ValidationError{Reason: "field OTPCode length must be exactly 6", Path: "VerifyOTPRequest.OTPCode", Type: "length"}

	// ErrVerifyOTPRequestOTPCodeNumericValidation is the error returned when the field OTPCode is not numeric.
	ErrVerifyOTPRequestOTPCodeNumericValidation = govaliderrors.ValidationError{Reason: "field OTPCode must be numeric", Path: "VerifyOTPRequest.OTPCode", Type: "numeric"}

	// ErrVerifyOTPRequestOTPCodeRequiredValidation is returned when the OTPCode is required but not provided.
	ErrVerifyOTPRequestOTPCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field OTPCode is required", Path: "VerifyOTPRequest.OTPCode", Type: "required"}

	// ErrVerifyOTPRequestTxnIDMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrVerifyOTPRequestTxnIDMaxLengthValidation = govaliderrors.ValidationError{Reason: "field TxnID must have a maximum length of 100", Path: "VerifyOTPRequest.TxnID", Type: "maxlength"}

	// ErrVerifyOTPRequestTxnIDMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrVerifyOTPRequestTxnIDMinLengthValidation = govaliderrors.ValidationError{Reason: "field TxnID must have a minimum length of 1", Path: "VerifyOTPRequest.TxnID", Type: "minlength"}

	// ErrVerifyOTPRequestTxnIDRequiredValidation is returned when the TxnID is required but not provided.
	ErrVerifyOTPRequestTxnIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TxnID is required", Path: "VerifyOTPRequest.TxnID", Type: "required"}
)

func ValidateVerifyOTPRequest(t *VerifyOTPRequest) error {
	if t == nil {
		return ErrNilVerifyOTPRequest
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.RequestID) > 50 {
		err := ErrVerifyOTPRequestRequestIDMaxLengthValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.RequestID) < 1 {
		err := ErrVerifyOTPRequestRequestIDMinLengthValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if t.RequestID == "" {
		err := ErrVerifyOTPRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.OTPCode) != 6 {
		err := ErrVerifyOTPRequestOTPCodeLengthValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if !validationhelper.IsNumeric(t.OTPCode) {
		err := ErrVerifyOTPRequestOTPCodeNumericValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if t.OTPCode == "" {
		err := ErrVerifyOTPRequestOTPCodeRequiredValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.TxnID) > 100 {
		err := ErrVerifyOTPRequestTxnIDMaxLengthValidation
		err.Value = t.TxnID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.TxnID) < 1 {
		err := ErrVerifyOTPRequestTxnIDMinLengthValidation
		err.Value = t.TxnID
		errs = append(errs, err)
	}

	if t.TxnID == "" {
		err := ErrVerifyOTPRequestTxnIDRequiredValidation
		err.Value = t.TxnID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*VerifyOTPRequest)(nil)

func (t *VerifyOTPRequest) Validate() error {
	return ValidateVerifyOTPRequest(t)
}
