// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCPCRejectRequest is returned when the CPCRejectRequest is nil.
	ErrNilCPCRejectRequest = errors.New("input CPCRejectRequest is nil")

	// ErrCPCRejectRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrCPCRejectRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "CPCRejectRequest.RequestID", Type: "required"}

	// ErrCPCRejectRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrCPCRejectRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "CPCRejectRequest.RequestID", Type: "uuid"}

	// ErrCPCRejectRequestRejectionReasonRequiredValidation is returned when the RejectionReason is required but not provided.
	ErrCPCRejectRequestRejectionReasonRequiredValidation = govaliderrors.ValidationError{Reason: "field RejectionReason is required", Path: "CPCRejectRequest.RejectionReason", Type: "required"}

	// ErrCPCRejectRequestRejectedByRequiredValidation is returned when the RejectedBy is required but not provided.
	ErrCPCRejectRequestRejectedByRequiredValidation = govaliderrors.ValidationError{Reason: "field RejectedBy is required", Path: "CPCRejectRequest.RejectedBy", Type: "required"}
)

func ValidateCPCRejectRequest(t *CPCRejectRequest) error {
	if t == nil {
		return ErrNilCPCRejectRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrCPCRejectRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrCPCRejectRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if t.RejectionReason == "" {
		err := ErrCPCRejectRequestRejectionReasonRequiredValidation
		err.Value = t.RejectionReason
		errs = append(errs, err)
	}

	if t.RejectedBy == "" {
		err := ErrCPCRejectRequestRejectedByRequiredValidation
		err.Value = t.RejectedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CPCRejectRequest)(nil)

func (t *CPCRejectRequest) Validate() error {
	return ValidateCPCRejectRequest(t)
}
