// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilAssignRequestRequest is returned when the AssignRequestRequest is nil.
	ErrNilAssignRequestRequest = errors.New("input AssignRequestRequest is nil")

	// ErrAssignRequestRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrAssignRequestRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "AssignRequestRequest.RequestID", Type: "required"}

	// ErrAssignRequestRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrAssignRequestRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "AssignRequestRequest.RequestID", Type: "uuid"}

	// ErrAssignRequestRequestAssignedToRequiredValidation is returned when the AssignedTo is required but not provided.
	ErrAssignRequestRequestAssignedToRequiredValidation = govaliderrors.ValidationError{Reason: "field AssignedTo is required", Path: "AssignRequestRequest.AssignedTo", Type: "required"}
)

func ValidateAssignRequestRequest(t *AssignRequestRequest) error {
	if t == nil {
		return ErrNilAssignRequestRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrAssignRequestRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrAssignRequestRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if t.AssignedTo == "" {
		err := ErrAssignRequestRequestAssignedToRequiredValidation
		err.Value = t.AssignedTo
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AssignRequestRequest)(nil)

func (t *AssignRequestRequest) Validate() error {
	return ValidateAssignRequestRequest(t)
}
