// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilApproveAddressChangeRequest is returned when the ApproveAddressChangeRequest is nil.
	ErrNilApproveAddressChangeRequest = errors.New("input ApproveAddressChangeRequest is nil")

	// ErrApproveAddressChangeRequestRequestIDMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrApproveAddressChangeRequestRequestIDMaxLengthValidation = govaliderrors.ValidationError{Reason: "field RequestID must have a maximum length of 50", Path: "ApproveAddressChangeRequest.RequestID", Type: "maxlength"}

	// ErrApproveAddressChangeRequestRequestIDMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrApproveAddressChangeRequestRequestIDMinLengthValidation = govaliderrors.ValidationError{Reason: "field RequestID must have a minimum length of 1", Path: "ApproveAddressChangeRequest.RequestID", Type: "minlength"}

	// ErrApproveAddressChangeRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrApproveAddressChangeRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "ApproveAddressChangeRequest.RequestID", Type: "required"}

	// ErrApproveAddressChangeRequestDecisionOneofValidation is the error returned when the field is not one of the allowed values.
	ErrApproveAddressChangeRequestDecisionOneofValidation = govaliderrors.ValidationError{Reason: "field Decision must be one of APPROVE REJECT SEND_BACK", Path: "ApproveAddressChangeRequest.Decision", Type: "oneof"}

	// ErrApproveAddressChangeRequestDecisionRequiredValidation is returned when the Decision is required but not provided.
	ErrApproveAddressChangeRequestDecisionRequiredValidation = govaliderrors.ValidationError{Reason: "field Decision is required", Path: "ApproveAddressChangeRequest.Decision", Type: "required"}

	// ErrApproveAddressChangeRequestApprovedByMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrApproveAddressChangeRequestApprovedByMaxLengthValidation = govaliderrors.ValidationError{Reason: "field ApprovedBy must have a maximum length of 50", Path: "ApproveAddressChangeRequest.ApprovedBy", Type: "maxlength"}

	// ErrApproveAddressChangeRequestApprovedByMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrApproveAddressChangeRequestApprovedByMinLengthValidation = govaliderrors.ValidationError{Reason: "field ApprovedBy must have a minimum length of 1", Path: "ApproveAddressChangeRequest.ApprovedBy", Type: "minlength"}

	// ErrApproveAddressChangeRequestApprovedByRequiredValidation is returned when the ApprovedBy is required but not provided.
	ErrApproveAddressChangeRequestApprovedByRequiredValidation = govaliderrors.ValidationError{Reason: "field ApprovedBy is required", Path: "ApproveAddressChangeRequest.ApprovedBy", Type: "required"}

	// ErrApproveAddressChangeRequestMissingDocumentsMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrApproveAddressChangeRequestMissingDocumentsMaxItemsValidation = govaliderrors.ValidationError{Reason: "field MissingDocuments must have a maximum of 100 items", Path: "ApproveAddressChangeRequest.MissingDocuments", Type: "maxitems"}

	// ErrApproveAddressChangeRequestMissingDocumentsMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrApproveAddressChangeRequestMissingDocumentsMinItemsValidation = govaliderrors.ValidationError{Reason: "field MissingDocuments must have a minimum of 1 items", Path: "ApproveAddressChangeRequest.MissingDocuments", Type: "minitems"}
)

func ValidateApproveAddressChangeRequest(t *ApproveAddressChangeRequest) error {
	if t == nil {
		return ErrNilApproveAddressChangeRequest
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.RequestID) > 50 {
		err := ErrApproveAddressChangeRequestRequestIDMaxLengthValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.RequestID) < 1 {
		err := ErrApproveAddressChangeRequestRequestIDMinLengthValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if t.RequestID == "" {
		err := ErrApproveAddressChangeRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !(t.Decision == "APPROVE" || t.Decision == "REJECT" || t.Decision == "SEND_BACK") {
		err := ErrApproveAddressChangeRequestDecisionOneofValidation
		err.Value = t.Decision
		errs = append(errs, err)
	}

	if t.Decision == "" {
		err := ErrApproveAddressChangeRequestDecisionRequiredValidation
		err.Value = t.Decision
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.ApprovedBy) > 50 {
		err := ErrApproveAddressChangeRequestApprovedByMaxLengthValidation
		err.Value = t.ApprovedBy
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.ApprovedBy) < 1 {
		err := ErrApproveAddressChangeRequestApprovedByMinLengthValidation
		err.Value = t.ApprovedBy
		errs = append(errs, err)
	}

	if t.ApprovedBy == "" {
		err := ErrApproveAddressChangeRequestApprovedByRequiredValidation
		err.Value = t.ApprovedBy
		errs = append(errs, err)
	}

	if len(t.MissingDocuments) != 0 && len(t.MissingDocuments) > 100 {
		err := ErrApproveAddressChangeRequestMissingDocumentsMaxItemsValidation
		err.Value = t.MissingDocuments
		errs = append(errs, err)
	}

	if len(t.MissingDocuments) != 0 && len(t.MissingDocuments) < 1 {
		err := ErrApproveAddressChangeRequestMissingDocumentsMinItemsValidation
		err.Value = t.MissingDocuments
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ApproveAddressChangeRequest)(nil)

func (t *ApproveAddressChangeRequest) Validate() error {
	return ValidateApproveAddressChangeRequest(t)
}
