// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilCPCSendBackRequest is returned when the CPCSendBackRequest is nil.
	ErrNilCPCSendBackRequest = errors.New("input CPCSendBackRequest is nil")

	// ErrCPCSendBackRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrCPCSendBackRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "CPCSendBackRequest.RequestID", Type: "required"}

	// ErrCPCSendBackRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrCPCSendBackRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "CPCSendBackRequest.RequestID", Type: "uuid"}

	// ErrCPCSendBackRequestMissingDocumentsMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrCPCSendBackRequestMissingDocumentsMinItemsValidation = govaliderrors.ValidationError{Reason: "field MissingDocuments must have a minimum of 1 items", Path: "CPCSendBackRequest.MissingDocuments", Type: "minitems"}

	// ErrCPCSendBackRequestMissingDocumentsRequiredValidation is returned when the MissingDocuments is required but not provided.
	ErrCPCSendBackRequestMissingDocumentsRequiredValidation = govaliderrors.ValidationError{Reason: "field MissingDocuments is required", Path: "CPCSendBackRequest.MissingDocuments", Type: "required"}

	// ErrCPCSendBackRequestMessageToCustomerRequiredValidation is returned when the MessageToCustomer is required but not provided.
	ErrCPCSendBackRequestMessageToCustomerRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageToCustomer is required", Path: "CPCSendBackRequest.MessageToCustomer", Type: "required"}

	// ErrCPCSendBackRequestRequestedByRequiredValidation is returned when the RequestedBy is required but not provided.
	ErrCPCSendBackRequestRequestedByRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestedBy is required", Path: "CPCSendBackRequest.RequestedBy", Type: "required"}
)

func ValidateCPCSendBackRequest(t *CPCSendBackRequest) error {
	if t == nil {
		return ErrNilCPCSendBackRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrCPCSendBackRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrCPCSendBackRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if len(t.MissingDocuments) < 1 {
		err := ErrCPCSendBackRequestMissingDocumentsMinItemsValidation
		err.Value = t.MissingDocuments
		errs = append(errs, err)
	}

	if t.MissingDocuments == nil {
		err := ErrCPCSendBackRequestMissingDocumentsRequiredValidation
		err.Value = t.MissingDocuments
		errs = append(errs, err)
	}

	if t.MessageToCustomer == "" {
		err := ErrCPCSendBackRequestMessageToCustomerRequiredValidation
		err.Value = t.MessageToCustomer
		errs = append(errs, err)
	}

	if t.RequestedBy == "" {
		err := ErrCPCSendBackRequestRequestedByRequiredValidation
		err.Value = t.RequestedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CPCSendBackRequest)(nil)

func (t *CPCSendBackRequest) Validate() error {
	return ValidateCPCSendBackRequest(t)
}
