// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetReceiptRequest is returned when the GetReceiptRequest is nil.
	ErrNilGetReceiptRequest = errors.New("input GetReceiptRequest is nil")

	// ErrGetReceiptRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrGetReceiptRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "GetReceiptRequest.RequestID", Type: "required"}

	// ErrGetReceiptRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrGetReceiptRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "GetReceiptRequest.RequestID", Type: "uuid"}
)

func ValidateGetReceiptRequest(t *GetReceiptRequest) error {
	if t == nil {
		return ErrNilGetReceiptRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrGetReceiptRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrGetReceiptRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetReceiptRequest)(nil)

func (t *GetReceiptRequest) Validate() error {
	return ValidateGetReceiptRequest(t)
}
