// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilInitiateNameChangeRequest is returned when the InitiateNameChangeRequest is nil.
	ErrNilInitiateNameChangeRequest = errors.New("input InitiateNameChangeRequest is nil")

	// ErrInitiateNameChangeRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrInitiateNameChangeRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "InitiateNameChangeRequest.CustomerID", Type: "required"}

	// ErrInitiateNameChangeRequestCustomerIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrInitiateNameChangeRequestCustomerIDUUIDValidation = govaliderrors.ValidationError{Reason: "field CustomerID must be a valid UUID", Path: "InitiateNameChangeRequest.CustomerID", Type: "uuid"}

	// ErrInitiateNameChangeRequestAuthMethodOneofValidation is the error returned when the field is not one of the allowed values.
	ErrInitiateNameChangeRequestAuthMethodOneofValidation = govaliderrors.ValidationError{Reason: "field AuthMethod must be one of AADHAAR MANUAL", Path: "InitiateNameChangeRequest.AuthMethod", Type: "oneof"}

	// ErrInitiateNameChangeRequestAuthMethodRequiredValidation is returned when the AuthMethod is required but not provided.
	ErrInitiateNameChangeRequestAuthMethodRequiredValidation = govaliderrors.ValidationError{Reason: "field AuthMethod is required", Path: "InitiateNameChangeRequest.AuthMethod", Type: "required"}

	// ErrInitiateNameChangeRequestChannelOneofValidation is the error returned when the field is not one of the allowed values.
	ErrInitiateNameChangeRequestChannelOneofValidation = govaliderrors.ValidationError{Reason: "field Channel must be one of Portal Mobile PostOffice CallCenter AgentPortal", Path: "InitiateNameChangeRequest.Channel", Type: "oneof"}

	// ErrInitiateNameChangeRequestChannelRequiredValidation is returned when the Channel is required but not provided.
	ErrInitiateNameChangeRequestChannelRequiredValidation = govaliderrors.ValidationError{Reason: "field Channel is required", Path: "InitiateNameChangeRequest.Channel", Type: "required"}
)

func ValidateInitiateNameChangeRequest(t *InitiateNameChangeRequest) error {
	if t == nil {
		return ErrNilInitiateNameChangeRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.CustomerID == "" {
		err := ErrInitiateNameChangeRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if !isValidUUID(t.CustomerID) {
		err := ErrInitiateNameChangeRequestCustomerIDUUIDValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if !(t.AuthMethod == "AADHAAR" || t.AuthMethod == "MANUAL") {
		err := ErrInitiateNameChangeRequestAuthMethodOneofValidation
		err.Value = t.AuthMethod
		errs = append(errs, err)
	}

	if t.AuthMethod == "" {
		err := ErrInitiateNameChangeRequestAuthMethodRequiredValidation
		err.Value = t.AuthMethod
		errs = append(errs, err)
	}

	if !(t.Channel == "Portal" || t.Channel == "Mobile" || t.Channel == "PostOffice" || t.Channel == "CallCenter" || t.Channel == "AgentPortal") {
		err := ErrInitiateNameChangeRequestChannelOneofValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if t.Channel == "" {
		err := ErrInitiateNameChangeRequestChannelRequiredValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*InitiateNameChangeRequest)(nil)

func (t *InitiateNameChangeRequest) Validate() error {
	return ValidateInitiateNameChangeRequest(t)
}
