// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilInitiateAddressChangeRequest is returned when the InitiateAddressChangeRequest is nil.
	ErrNilInitiateAddressChangeRequest = errors.New("input InitiateAddressChangeRequest is nil")

	// ErrInitiateAddressChangeRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrInitiateAddressChangeRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "InitiateAddressChangeRequest.CustomerID", Type: "required"}

	// isValidUUID validates UUID format manually for maximum performance
	// Validates RFC 4122 format: 8-4-4-4-12 hex digits with hyphens
	isValidUUID = func(s string) bool {
		// Check length: 36 characters (32 hex + 4 hyphens)
		if len(s) != 36 {
			return false
		}

		// Check hyphen positions: 8-4-4-4-12
		if s[8] != '-' || s[13] != '-' || s[18] != '-' || s[23] != '-' {
			return false
		}

		// Check hex characters and version/variant
		for i := 0; i < 36; i++ {
			if i == 8 || i == 13 || i == 18 || i == 23 {
				continue // skip hyphens
			}

			c := s[i]
			if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
				return false
			}
		}

		// Check version (position 14): must be 1-5
		version := s[14]
		if version < '1' || version > '5' {
			return false
		}

		// Check variant (position 19): must be 8, 9, A, B (case insensitive)
		variant := s[19]
		if !(variant == '8' || variant == '9' ||
			variant == 'A' || variant == 'a' ||
			variant == 'B' || variant == 'b') {
			return false
		}

		return true
	}
	// ErrInitiateAddressChangeRequestCustomerIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrInitiateAddressChangeRequestCustomerIDUUIDValidation = govaliderrors.ValidationError{Reason: "field CustomerID must be a valid UUID", Path: "InitiateAddressChangeRequest.CustomerID", Type: "uuid"}

	// ErrInitiateAddressChangeRequestAuthMethodOneofValidation is the error returned when the field is not one of the allowed values.
	ErrInitiateAddressChangeRequestAuthMethodOneofValidation = govaliderrors.ValidationError{Reason: "field AuthMethod must be one of AADHAAR MANUAL", Path: "InitiateAddressChangeRequest.AuthMethod", Type: "oneof"}

	// ErrInitiateAddressChangeRequestAuthMethodRequiredValidation is returned when the AuthMethod is required but not provided.
	ErrInitiateAddressChangeRequestAuthMethodRequiredValidation = govaliderrors.ValidationError{Reason: "field AuthMethod is required", Path: "InitiateAddressChangeRequest.AuthMethod", Type: "required"}

	// ErrInitiateAddressChangeRequestAddressUpdateForOneofValidation is the error returned when the field is not one of the allowed values.
	ErrInitiateAddressChangeRequestAddressUpdateForOneofValidation = govaliderrors.ValidationError{Reason: "field AddressUpdateFor must be one of INSURED PROPOSER ASSIGNEE TRUSTEE", Path: "InitiateAddressChangeRequest.AddressUpdateFor", Type: "oneof"}

	// ErrInitiateAddressChangeRequestAddressUpdateForRequiredValidation is returned when the AddressUpdateFor is required but not provided.
	ErrInitiateAddressChangeRequestAddressUpdateForRequiredValidation = govaliderrors.ValidationError{Reason: "field AddressUpdateFor is required", Path: "InitiateAddressChangeRequest.AddressUpdateFor", Type: "required"}

	// ErrInitiateAddressChangeRequestAddressTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrInitiateAddressChangeRequestAddressTypeOneofValidation = govaliderrors.ValidationError{Reason: "field AddressType must be one of COMMUNICATION PERMANENT OFFICIAL", Path: "InitiateAddressChangeRequest.AddressType", Type: "oneof"}

	// ErrInitiateAddressChangeRequestAddressTypeRequiredValidation is returned when the AddressType is required but not provided.
	ErrInitiateAddressChangeRequestAddressTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field AddressType is required", Path: "InitiateAddressChangeRequest.AddressType", Type: "required"}

	// ErrInitiateAddressChangeRequestNewAddressLine1MaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrInitiateAddressChangeRequestNewAddressLine1MaxLengthValidation = govaliderrors.ValidationError{Reason: "field NewAddressLine1 must have a maximum length of 200", Path: "InitiateAddressChangeRequest.NewAddressLine1", Type: "maxlength"}

	// ErrInitiateAddressChangeRequestNewAddressLine1MinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrInitiateAddressChangeRequestNewAddressLine1MinLengthValidation = govaliderrors.ValidationError{Reason: "field NewAddressLine1 must have a minimum length of 1", Path: "InitiateAddressChangeRequest.NewAddressLine1", Type: "minlength"}

	// ErrInitiateAddressChangeRequestNewAddressLine1RequiredValidation is returned when the NewAddressLine1 is required but not provided.
	ErrInitiateAddressChangeRequestNewAddressLine1RequiredValidation = govaliderrors.ValidationError{Reason: "field NewAddressLine1 is required", Path: "InitiateAddressChangeRequest.NewAddressLine1", Type: "required"}

	// ErrInitiateAddressChangeRequestNewCityMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrInitiateAddressChangeRequestNewCityMaxLengthValidation = govaliderrors.ValidationError{Reason: "field NewCity must have a maximum length of 100", Path: "InitiateAddressChangeRequest.NewCity", Type: "maxlength"}

	// ErrInitiateAddressChangeRequestNewCityMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrInitiateAddressChangeRequestNewCityMinLengthValidation = govaliderrors.ValidationError{Reason: "field NewCity must have a minimum length of 1", Path: "InitiateAddressChangeRequest.NewCity", Type: "minlength"}

	// ErrInitiateAddressChangeRequestNewCityRequiredValidation is returned when the NewCity is required but not provided.
	ErrInitiateAddressChangeRequestNewCityRequiredValidation = govaliderrors.ValidationError{Reason: "field NewCity is required", Path: "InitiateAddressChangeRequest.NewCity", Type: "required"}

	// ErrInitiateAddressChangeRequestNewDistrictMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrInitiateAddressChangeRequestNewDistrictMaxLengthValidation = govaliderrors.ValidationError{Reason: "field NewDistrict must have a maximum length of 100", Path: "InitiateAddressChangeRequest.NewDistrict", Type: "maxlength"}

	// ErrInitiateAddressChangeRequestNewDistrictMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrInitiateAddressChangeRequestNewDistrictMinLengthValidation = govaliderrors.ValidationError{Reason: "field NewDistrict must have a minimum length of 1", Path: "InitiateAddressChangeRequest.NewDistrict", Type: "minlength"}

	// ErrInitiateAddressChangeRequestNewDistrictRequiredValidation is returned when the NewDistrict is required but not provided.
	ErrInitiateAddressChangeRequestNewDistrictRequiredValidation = govaliderrors.ValidationError{Reason: "field NewDistrict is required", Path: "InitiateAddressChangeRequest.NewDistrict", Type: "required"}

	// ErrInitiateAddressChangeRequestNewStateMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrInitiateAddressChangeRequestNewStateMaxLengthValidation = govaliderrors.ValidationError{Reason: "field NewState must have a maximum length of 50", Path: "InitiateAddressChangeRequest.NewState", Type: "maxlength"}

	// ErrInitiateAddressChangeRequestNewStateMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrInitiateAddressChangeRequestNewStateMinLengthValidation = govaliderrors.ValidationError{Reason: "field NewState must have a minimum length of 1", Path: "InitiateAddressChangeRequest.NewState", Type: "minlength"}

	// ErrInitiateAddressChangeRequestNewStateRequiredValidation is returned when the NewState is required but not provided.
	ErrInitiateAddressChangeRequestNewStateRequiredValidation = govaliderrors.ValidationError{Reason: "field NewState is required", Path: "InitiateAddressChangeRequest.NewState", Type: "required"}

	// ErrInitiateAddressChangeRequestNewPincodeLengthValidation is the error returned when the length of the field is not exactly 6.
	ErrInitiateAddressChangeRequestNewPincodeLengthValidation = govaliderrors.ValidationError{Reason: "field NewPincode length must be exactly 6", Path: "InitiateAddressChangeRequest.NewPincode", Type: "length"}

	// ErrInitiateAddressChangeRequestNewPincodeNumericValidation is the error returned when the field NewPincode is not numeric.
	ErrInitiateAddressChangeRequestNewPincodeNumericValidation = govaliderrors.ValidationError{Reason: "field NewPincode must be numeric", Path: "InitiateAddressChangeRequest.NewPincode", Type: "numeric"}

	// ErrInitiateAddressChangeRequestNewPincodeRequiredValidation is returned when the NewPincode is required but not provided.
	ErrInitiateAddressChangeRequestNewPincodeRequiredValidation = govaliderrors.ValidationError{Reason: "field NewPincode is required", Path: "InitiateAddressChangeRequest.NewPincode", Type: "required"}

	// ErrInitiateAddressChangeRequestChannelOneofValidation is the error returned when the field is not one of the allowed values.
	ErrInitiateAddressChangeRequestChannelOneofValidation = govaliderrors.ValidationError{Reason: "field Channel must be one of Portal Mobile PostOffice CallCenter AgentPortal", Path: "InitiateAddressChangeRequest.Channel", Type: "oneof"}

	// ErrInitiateAddressChangeRequestChannelRequiredValidation is returned when the Channel is required but not provided.
	ErrInitiateAddressChangeRequestChannelRequiredValidation = govaliderrors.ValidationError{Reason: "field Channel is required", Path: "InitiateAddressChangeRequest.Channel", Type: "required"}
)

func ValidateInitiateAddressChangeRequest(t *InitiateAddressChangeRequest) error {
	if t == nil {
		return ErrNilInitiateAddressChangeRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.CustomerID == "" {
		err := ErrInitiateAddressChangeRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if !isValidUUID(t.CustomerID) {
		err := ErrInitiateAddressChangeRequestCustomerIDUUIDValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if !(t.AuthMethod == "AADHAAR" || t.AuthMethod == "MANUAL") {
		err := ErrInitiateAddressChangeRequestAuthMethodOneofValidation
		err.Value = t.AuthMethod
		errs = append(errs, err)
	}

	if t.AuthMethod == "" {
		err := ErrInitiateAddressChangeRequestAuthMethodRequiredValidation
		err.Value = t.AuthMethod
		errs = append(errs, err)
	}

	if !(t.AddressUpdateFor == "INSURED" || t.AddressUpdateFor == "PROPOSER" || t.AddressUpdateFor == "ASSIGNEE" || t.AddressUpdateFor == "TRUSTEE") {
		err := ErrInitiateAddressChangeRequestAddressUpdateForOneofValidation
		err.Value = t.AddressUpdateFor
		errs = append(errs, err)
	}

	if t.AddressUpdateFor == "" {
		err := ErrInitiateAddressChangeRequestAddressUpdateForRequiredValidation
		err.Value = t.AddressUpdateFor
		errs = append(errs, err)
	}

	if !(t.AddressType == "COMMUNICATION" || t.AddressType == "PERMANENT" || t.AddressType == "OFFICIAL") {
		err := ErrInitiateAddressChangeRequestAddressTypeOneofValidation
		err.Value = t.AddressType
		errs = append(errs, err)
	}

	if t.AddressType == "" {
		err := ErrInitiateAddressChangeRequestAddressTypeRequiredValidation
		err.Value = t.AddressType
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewAddressLine1) > 200 {
		err := ErrInitiateAddressChangeRequestNewAddressLine1MaxLengthValidation
		err.Value = t.NewAddressLine1
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewAddressLine1) < 1 {
		err := ErrInitiateAddressChangeRequestNewAddressLine1MinLengthValidation
		err.Value = t.NewAddressLine1
		errs = append(errs, err)
	}

	if t.NewAddressLine1 == "" {
		err := ErrInitiateAddressChangeRequestNewAddressLine1RequiredValidation
		err.Value = t.NewAddressLine1
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewCity) > 100 {
		err := ErrInitiateAddressChangeRequestNewCityMaxLengthValidation
		err.Value = t.NewCity
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewCity) < 1 {
		err := ErrInitiateAddressChangeRequestNewCityMinLengthValidation
		err.Value = t.NewCity
		errs = append(errs, err)
	}

	if t.NewCity == "" {
		err := ErrInitiateAddressChangeRequestNewCityRequiredValidation
		err.Value = t.NewCity
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewDistrict) > 100 {
		err := ErrInitiateAddressChangeRequestNewDistrictMaxLengthValidation
		err.Value = t.NewDistrict
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewDistrict) < 1 {
		err := ErrInitiateAddressChangeRequestNewDistrictMinLengthValidation
		err.Value = t.NewDistrict
		errs = append(errs, err)
	}

	if t.NewDistrict == "" {
		err := ErrInitiateAddressChangeRequestNewDistrictRequiredValidation
		err.Value = t.NewDistrict
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewState) > 50 {
		err := ErrInitiateAddressChangeRequestNewStateMaxLengthValidation
		err.Value = t.NewState
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewState) < 1 {
		err := ErrInitiateAddressChangeRequestNewStateMinLengthValidation
		err.Value = t.NewState
		errs = append(errs, err)
	}

	if t.NewState == "" {
		err := ErrInitiateAddressChangeRequestNewStateRequiredValidation
		err.Value = t.NewState
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewPincode) != 6 {
		err := ErrInitiateAddressChangeRequestNewPincodeLengthValidation
		err.Value = t.NewPincode
		errs = append(errs, err)
	}

	if !validationhelper.IsNumeric(t.NewPincode) {
		err := ErrInitiateAddressChangeRequestNewPincodeNumericValidation
		err.Value = t.NewPincode
		errs = append(errs, err)
	}

	if t.NewPincode == "" {
		err := ErrInitiateAddressChangeRequestNewPincodeRequiredValidation
		err.Value = t.NewPincode
		errs = append(errs, err)
	}

	if !(t.Channel == "Portal" || t.Channel == "Mobile" || t.Channel == "PostOffice" || t.Channel == "CallCenter" || t.Channel == "AgentPortal") {
		err := ErrInitiateAddressChangeRequestChannelOneofValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if t.Channel == "" {
		err := ErrInitiateAddressChangeRequestChannelRequiredValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*InitiateAddressChangeRequest)(nil)

func (t *InitiateAddressChangeRequest) Validate() error {
	return ValidateInitiateAddressChangeRequest(t)
}
