// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilUploadDocumentRequest is returned when the UploadDocumentRequest is nil.
	ErrNilUploadDocumentRequest = errors.New("input UploadDocumentRequest is nil")

	// ErrUploadDocumentRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrUploadDocumentRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "UploadDocumentRequest.RequestID", Type: "required"}

	// ErrUploadDocumentRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrUploadDocumentRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "UploadDocumentRequest.RequestID", Type: "uuid"}

	// ErrUploadDocumentRequestDocumentTypeRequiredValidation is returned when the DocumentType is required but not provided.
	ErrUploadDocumentRequestDocumentTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentType is required", Path: "UploadDocumentRequest.DocumentType", Type: "required"}

	// ErrUploadDocumentRequestUploadedByRequiredValidation is returned when the UploadedBy is required but not provided.
	ErrUploadDocumentRequestUploadedByRequiredValidation = govaliderrors.ValidationError{Reason: "field UploadedBy is required", Path: "UploadDocumentRequest.UploadedBy", Type: "required"}
)

func ValidateUploadDocumentRequest(t *UploadDocumentRequest) error {
	if t == nil {
		return ErrNilUploadDocumentRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrUploadDocumentRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrUploadDocumentRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if t.DocumentType == "" {
		err := ErrUploadDocumentRequestDocumentTypeRequiredValidation
		err.Value = t.DocumentType
		errs = append(errs, err)
	}

	if t.UploadedBy == "" {
		err := ErrUploadDocumentRequestUploadedByRequiredValidation
		err.Value = t.UploadedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*UploadDocumentRequest)(nil)

func (t *UploadDocumentRequest) Validate() error {
	return ValidateUploadDocumentRequest(t)
}
