// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDeleteDocumentRequest is returned when the DeleteDocumentRequest is nil.
	ErrNilDeleteDocumentRequest = errors.New("input DeleteDocumentRequest is nil")

	// ErrDeleteDocumentRequestDocumentIDRequiredValidation is returned when the DocumentID is required but not provided.
	ErrDeleteDocumentRequestDocumentIDRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentID is required", Path: "DeleteDocumentRequest.DocumentID", Type: "required"}

	// ErrDeleteDocumentRequestDocumentIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrDeleteDocumentRequestDocumentIDUUIDValidation = govaliderrors.ValidationError{Reason: "field DocumentID must be a valid UUID", Path: "DeleteDocumentRequest.DocumentID", Type: "uuid"}
)

func ValidateDeleteDocumentRequest(t *DeleteDocumentRequest) error {
	if t == nil {
		return ErrNilDeleteDocumentRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.DocumentID == "" {
		err := ErrDeleteDocumentRequestDocumentIDRequiredValidation
		err.Value = t.DocumentID
		errs = append(errs, err)
	}

	if !isValidUUID(t.DocumentID) {
		err := ErrDeleteDocumentRequestDocumentIDUUIDValidation
		err.Value = t.DocumentID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DeleteDocumentRequest)(nil)

func (t *DeleteDocumentRequest) Validate() error {
	return ValidateDeleteDocumentRequest(t)
}
