// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilNewNamePayload is returned when the NewNamePayload is nil.
	ErrNilNewNamePayload = errors.New("input NewNamePayload is nil")

	// ErrNewNamePayloadSalutationOneofValidation is the error returned when the field is not one of the allowed values.
	ErrNewNamePayloadSalutationOneofValidation = govaliderrors.ValidationError{Reason: "field Salutation must be one of Mr Mrs Ms Shri Smt Dr", Path: "NewNamePayload.Salutation", Type: "oneof"}

	// ErrNewNamePayloadSalutationRequiredValidation is returned when the Salutation is required but not provided.
	ErrNewNamePayloadSalutationRequiredValidation = govaliderrors.ValidationError{Reason: "field Salutation is required", Path: "NewNamePayload.Salutation", Type: "required"}

	// ErrNewNamePayloadFirstNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrNewNamePayloadFirstNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field FirstName must have a maximum length of 100", Path: "NewNamePayload.FirstName", Type: "maxlength"}

	// ErrNewNamePayloadFirstNameRequiredValidation is returned when the FirstName is required but not provided.
	ErrNewNamePayloadFirstNameRequiredValidation = govaliderrors.ValidationError{Reason: "field FirstName is required", Path: "NewNamePayload.FirstName", Type: "required"}

	// ErrNewNamePayloadLastNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrNewNamePayloadLastNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field LastName must have a maximum length of 100", Path: "NewNamePayload.LastName", Type: "maxlength"}

	// ErrNewNamePayloadLastNameRequiredValidation is returned when the LastName is required but not provided.
	ErrNewNamePayloadLastNameRequiredValidation = govaliderrors.ValidationError{Reason: "field LastName is required", Path: "NewNamePayload.LastName", Type: "required"}
)

func ValidateNewNamePayload(t *NewNamePayload) error {
	if t == nil {
		return ErrNilNewNamePayload
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Salutation == "Mr" || t.Salutation == "Mrs" || t.Salutation == "Ms" || t.Salutation == "Shri" || t.Salutation == "Smt" || t.Salutation == "Dr") {
		err := ErrNewNamePayloadSalutationOneofValidation
		err.Value = t.Salutation
		errs = append(errs, err)
	}

	if t.Salutation == "" {
		err := ErrNewNamePayloadSalutationRequiredValidation
		err.Value = t.Salutation
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.FirstName) > 100 {
		err := ErrNewNamePayloadFirstNameMaxLengthValidation
		err.Value = t.FirstName
		errs = append(errs, err)
	}

	if t.FirstName == "" {
		err := ErrNewNamePayloadFirstNameRequiredValidation
		err.Value = t.FirstName
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.LastName) > 100 {
		err := ErrNewNamePayloadLastNameMaxLengthValidation
		err.Value = t.LastName
		errs = append(errs, err)
	}

	if t.LastName == "" {
		err := ErrNewNamePayloadLastNameRequiredValidation
		err.Value = t.LastName
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*NewNamePayload)(nil)

func (t *NewNamePayload) Validate() error {
	return ValidateNewNamePayload(t)
}
