// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilRequestMissingDocumentsRequest is returned when the RequestMissingDocumentsRequest is nil.
	ErrNilRequestMissingDocumentsRequest = errors.New("input RequestMissingDocumentsRequest is nil")

	// ErrRequestMissingDocumentsRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrRequestMissingDocumentsRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "RequestMissingDocumentsRequest.RequestID", Type: "required"}

	// ErrRequestMissingDocumentsRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrRequestMissingDocumentsRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "RequestMissingDocumentsRequest.RequestID", Type: "uuid"}

	// ErrRequestMissingDocumentsRequestMissingDocumentsMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrRequestMissingDocumentsRequestMissingDocumentsMinItemsValidation = govaliderrors.ValidationError{Reason: "field MissingDocuments must have a minimum of 1 items", Path: "RequestMissingDocumentsRequest.MissingDocuments", Type: "minitems"}

	// ErrRequestMissingDocumentsRequestMissingDocumentsRequiredValidation is returned when the MissingDocuments is required but not provided.
	ErrRequestMissingDocumentsRequestMissingDocumentsRequiredValidation = govaliderrors.ValidationError{Reason: "field MissingDocuments is required", Path: "RequestMissingDocumentsRequest.MissingDocuments", Type: "required"}

	// ErrRequestMissingDocumentsRequestMessageToCustomerRequiredValidation is returned when the MessageToCustomer is required but not provided.
	ErrRequestMissingDocumentsRequestMessageToCustomerRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageToCustomer is required", Path: "RequestMissingDocumentsRequest.MessageToCustomer", Type: "required"}

	// ErrRequestMissingDocumentsRequestRequestedByRequiredValidation is returned when the RequestedBy is required but not provided.
	ErrRequestMissingDocumentsRequestRequestedByRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestedBy is required", Path: "RequestMissingDocumentsRequest.RequestedBy", Type: "required"}
)

func ValidateRequestMissingDocumentsRequest(t *RequestMissingDocumentsRequest) error {
	if t == nil {
		return ErrNilRequestMissingDocumentsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrRequestMissingDocumentsRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrRequestMissingDocumentsRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if len(t.MissingDocuments) < 1 {
		err := ErrRequestMissingDocumentsRequestMissingDocumentsMinItemsValidation
		err.Value = t.MissingDocuments
		errs = append(errs, err)
	}

	if t.MissingDocuments == nil {
		err := ErrRequestMissingDocumentsRequestMissingDocumentsRequiredValidation
		err.Value = t.MissingDocuments
		errs = append(errs, err)
	}

	if t.MessageToCustomer == "" {
		err := ErrRequestMissingDocumentsRequestMessageToCustomerRequiredValidation
		err.Value = t.MessageToCustomer
		errs = append(errs, err)
	}

	if t.RequestedBy == "" {
		err := ErrRequestMissingDocumentsRequestRequestedByRequiredValidation
		err.Value = t.RequestedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RequestMissingDocumentsRequest)(nil)

func (t *RequestMissingDocumentsRequest) Validate() error {
	return ValidateRequestMissingDocumentsRequest(t)
}
