// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetDocumentMetadataRequest is returned when the GetDocumentMetadataRequest is nil.
	ErrNilGetDocumentMetadataRequest = errors.New("input GetDocumentMetadataRequest is nil")

	// ErrGetDocumentMetadataRequestDocumentIDRequiredValidation is returned when the DocumentID is required but not provided.
	ErrGetDocumentMetadataRequestDocumentIDRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentID is required", Path: "GetDocumentMetadataRequest.DocumentID", Type: "required"}

	// ErrGetDocumentMetadataRequestDocumentIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrGetDocumentMetadataRequestDocumentIDUUIDValidation = govaliderrors.ValidationError{Reason: "field DocumentID must be a valid UUID", Path: "GetDocumentMetadataRequest.DocumentID", Type: "uuid"}
)

func ValidateGetDocumentMetadataRequest(t *GetDocumentMetadataRequest) error {
	if t == nil {
		return ErrNilGetDocumentMetadataRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.DocumentID == "" {
		err := ErrGetDocumentMetadataRequestDocumentIDRequiredValidation
		err.Value = t.DocumentID
		errs = append(errs, err)
	}

	if !isValidUUID(t.DocumentID) {
		err := ErrGetDocumentMetadataRequestDocumentIDUUIDValidation
		err.Value = t.DocumentID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetDocumentMetadataRequest)(nil)

func (t *GetDocumentMetadataRequest) Validate() error {
	return ValidateGetDocumentMetadataRequest(t)
}
