// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilSubmitAddressChangeRequest is returned when the SubmitAddressChangeRequest is nil.
	ErrNilSubmitAddressChangeRequest = errors.New("input SubmitAddressChangeRequest is nil")

	// ErrSubmitAddressChangeRequestRequestIDMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrSubmitAddressChangeRequestRequestIDMaxLengthValidation = govaliderrors.ValidationError{Reason: "field RequestID must have a maximum length of 50", Path: "SubmitAddressChangeRequest.RequestID", Type: "maxlength"}

	// ErrSubmitAddressChangeRequestRequestIDMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrSubmitAddressChangeRequestRequestIDMinLengthValidation = govaliderrors.ValidationError{Reason: "field RequestID must have a minimum length of 1", Path: "SubmitAddressChangeRequest.RequestID", Type: "minlength"}

	// ErrSubmitAddressChangeRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrSubmitAddressChangeRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "SubmitAddressChangeRequest.RequestID", Type: "required"}

	// ErrSubmitAddressChangeRequestUploadedDocumentsMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrSubmitAddressChangeRequestUploadedDocumentsMaxItemsValidation = govaliderrors.ValidationError{Reason: "field UploadedDocuments must have a maximum of 50 items", Path: "SubmitAddressChangeRequest.UploadedDocuments", Type: "maxitems"}

	// ErrSubmitAddressChangeRequestUploadedDocumentsMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrSubmitAddressChangeRequestUploadedDocumentsMinItemsValidation = govaliderrors.ValidationError{Reason: "field UploadedDocuments must have a minimum of 1 items", Path: "SubmitAddressChangeRequest.UploadedDocuments", Type: "minitems"}

	// ErrSubmitAddressChangeRequestUploadedDocumentsRequiredValidation is returned when the UploadedDocuments is required but not provided.
	ErrSubmitAddressChangeRequestUploadedDocumentsRequiredValidation = govaliderrors.ValidationError{Reason: "field UploadedDocuments is required", Path: "SubmitAddressChangeRequest.UploadedDocuments", Type: "required"}

	// ErrSubmitAddressChangeRequestDeclarationRequiredValidation is returned when the Declaration is required but not provided.
	ErrSubmitAddressChangeRequestDeclarationRequiredValidation = govaliderrors.ValidationError{Reason: "field Declaration is required", Path: "SubmitAddressChangeRequest.Declaration", Type: "required"}

	// ErrSubmitAddressChangeRequestSubmittedByMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrSubmitAddressChangeRequestSubmittedByMaxLengthValidation = govaliderrors.ValidationError{Reason: "field SubmittedBy must have a maximum length of 50", Path: "SubmitAddressChangeRequest.SubmittedBy", Type: "maxlength"}

	// ErrSubmitAddressChangeRequestSubmittedByMinLengthValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrSubmitAddressChangeRequestSubmittedByMinLengthValidation = govaliderrors.ValidationError{Reason: "field SubmittedBy must have a minimum length of 1", Path: "SubmitAddressChangeRequest.SubmittedBy", Type: "minlength"}

	// ErrSubmitAddressChangeRequestSubmittedByRequiredValidation is returned when the SubmittedBy is required but not provided.
	ErrSubmitAddressChangeRequestSubmittedByRequiredValidation = govaliderrors.ValidationError{Reason: "field SubmittedBy is required", Path: "SubmitAddressChangeRequest.SubmittedBy", Type: "required"}
)

func ValidateSubmitAddressChangeRequest(t *SubmitAddressChangeRequest) error {
	if t == nil {
		return ErrNilSubmitAddressChangeRequest
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.RequestID) > 50 {
		err := ErrSubmitAddressChangeRequestRequestIDMaxLengthValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.RequestID) < 1 {
		err := ErrSubmitAddressChangeRequestRequestIDMinLengthValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if t.RequestID == "" {
		err := ErrSubmitAddressChangeRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if len(t.UploadedDocuments) > 50 {
		err := ErrSubmitAddressChangeRequestUploadedDocumentsMaxItemsValidation
		err.Value = t.UploadedDocuments
		errs = append(errs, err)
	}

	if len(t.UploadedDocuments) < 1 {
		err := ErrSubmitAddressChangeRequestUploadedDocumentsMinItemsValidation
		err.Value = t.UploadedDocuments
		errs = append(errs, err)
	}

	if t.UploadedDocuments == nil {
		err := ErrSubmitAddressChangeRequestUploadedDocumentsRequiredValidation
		err.Value = t.UploadedDocuments
		errs = append(errs, err)
	}

	if t.Declaration == false {
		err := ErrSubmitAddressChangeRequestDeclarationRequiredValidation
		err.Value = t.Declaration
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.SubmittedBy) > 50 {
		err := ErrSubmitAddressChangeRequestSubmittedByMaxLengthValidation
		err.Value = t.SubmittedBy
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.SubmittedBy) < 1 {
		err := ErrSubmitAddressChangeRequestSubmittedByMinLengthValidation
		err.Value = t.SubmittedBy
		errs = append(errs, err)
	}

	if t.SubmittedBy == "" {
		err := ErrSubmitAddressChangeRequestSubmittedByRequiredValidation
		err.Value = t.SubmittedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SubmitAddressChangeRequest)(nil)

func (t *SubmitAddressChangeRequest) Validate() error {
	return ValidateSubmitAddressChangeRequest(t)
}
