// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilWithdrawRequest is returned when the WithdrawRequest is nil.
	ErrNilWithdrawRequest = errors.New("input WithdrawRequest is nil")

	// ErrWithdrawRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrWithdrawRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "WithdrawRequest.RequestID", Type: "required"}

	// ErrWithdrawRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrWithdrawRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "WithdrawRequest.RequestID", Type: "uuid"}

	// ErrWithdrawRequestWithdrawalReasonRequiredValidation is returned when the WithdrawalReason is required but not provided.
	ErrWithdrawRequestWithdrawalReasonRequiredValidation = govaliderrors.ValidationError{Reason: "field WithdrawalReason is required", Path: "WithdrawRequest.WithdrawalReason", Type: "required"}

	// ErrWithdrawRequestRequestedByRequiredValidation is returned when the RequestedBy is required but not provided.
	ErrWithdrawRequestRequestedByRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestedBy is required", Path: "WithdrawRequest.RequestedBy", Type: "required"}
)

func ValidateWithdrawRequest(t *WithdrawRequest) error {
	if t == nil {
		return ErrNilWithdrawRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrWithdrawRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrWithdrawRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if t.WithdrawalReason == "" {
		err := ErrWithdrawRequestWithdrawalReasonRequiredValidation
		err.Value = t.WithdrawalReason
		errs = append(errs, err)
	}

	if t.RequestedBy == "" {
		err := ErrWithdrawRequestRequestedByRequiredValidation
		err.Value = t.RequestedBy
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*WithdrawRequest)(nil)

func (t *WithdrawRequest) Validate() error {
	return ValidateWithdrawRequest(t)
}
