// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilValidateAddressRequest is returned when the ValidateAddressRequest is nil.
	ErrNilValidateAddressRequest = errors.New("input ValidateAddressRequest is nil")

	// ErrValidateAddressRequestAddressLine1MaxLengthValidation is the error returned when the length of the field exceeds the maximum of 150.
	ErrValidateAddressRequestAddressLine1MaxLengthValidation = govaliderrors.ValidationError{Reason: "field AddressLine1 must have a maximum length of 150", Path: "ValidateAddressRequest.AddressLine1", Type: "maxlength"}

	// ErrValidateAddressRequestAddressLine1RequiredValidation is returned when the AddressLine1 is required but not provided.
	ErrValidateAddressRequestAddressLine1RequiredValidation = govaliderrors.ValidationError{Reason: "field AddressLine1 is required", Path: "ValidateAddressRequest.AddressLine1", Type: "required"}

	// ErrValidateAddressRequestCityMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrValidateAddressRequestCityMaxLengthValidation = govaliderrors.ValidationError{Reason: "field City must have a maximum length of 100", Path: "ValidateAddressRequest.City", Type: "maxlength"}

	// ErrValidateAddressRequestCityRequiredValidation is returned when the City is required but not provided.
	ErrValidateAddressRequestCityRequiredValidation = govaliderrors.ValidationError{Reason: "field City is required", Path: "ValidateAddressRequest.City", Type: "required"}

	// ErrValidateAddressRequestDistrictMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrValidateAddressRequestDistrictMaxLengthValidation = govaliderrors.ValidationError{Reason: "field District must have a maximum length of 100", Path: "ValidateAddressRequest.District", Type: "maxlength"}

	// ErrValidateAddressRequestDistrictRequiredValidation is returned when the District is required but not provided.
	ErrValidateAddressRequestDistrictRequiredValidation = govaliderrors.ValidationError{Reason: "field District is required", Path: "ValidateAddressRequest.District", Type: "required"}

	// ErrValidateAddressRequestStateRequiredValidation is returned when the State is required but not provided.
	ErrValidateAddressRequestStateRequiredValidation = govaliderrors.ValidationError{Reason: "field State is required", Path: "ValidateAddressRequest.State", Type: "required"}

	// ErrValidateAddressRequestPincodeLengthValidation is the error returned when the length of the field is not exactly 6.
	ErrValidateAddressRequestPincodeLengthValidation = govaliderrors.ValidationError{Reason: "field Pincode length must be exactly 6", Path: "ValidateAddressRequest.Pincode", Type: "length"}

	// ErrValidateAddressRequestPincodeNumericValidation is the error returned when the field Pincode is not numeric.
	ErrValidateAddressRequestPincodeNumericValidation = govaliderrors.ValidationError{Reason: "field Pincode must be numeric", Path: "ValidateAddressRequest.Pincode", Type: "numeric"}

	// ErrValidateAddressRequestPincodeRequiredValidation is returned when the Pincode is required but not provided.
	ErrValidateAddressRequestPincodeRequiredValidation = govaliderrors.ValidationError{Reason: "field Pincode is required", Path: "ValidateAddressRequest.Pincode", Type: "required"}
)

func ValidateValidateAddressRequest(t *ValidateAddressRequest) error {
	if t == nil {
		return ErrNilValidateAddressRequest
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.AddressLine1) > 150 {
		err := ErrValidateAddressRequestAddressLine1MaxLengthValidation
		err.Value = t.AddressLine1
		errs = append(errs, err)
	}

	if t.AddressLine1 == "" {
		err := ErrValidateAddressRequestAddressLine1RequiredValidation
		err.Value = t.AddressLine1
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.City) > 100 {
		err := ErrValidateAddressRequestCityMaxLengthValidation
		err.Value = t.City
		errs = append(errs, err)
	}

	if t.City == "" {
		err := ErrValidateAddressRequestCityRequiredValidation
		err.Value = t.City
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.District) > 100 {
		err := ErrValidateAddressRequestDistrictMaxLengthValidation
		err.Value = t.District
		errs = append(errs, err)
	}

	if t.District == "" {
		err := ErrValidateAddressRequestDistrictRequiredValidation
		err.Value = t.District
		errs = append(errs, err)
	}

	if t.State == "" {
		err := ErrValidateAddressRequestStateRequiredValidation
		err.Value = t.State
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.Pincode) != 6 {
		err := ErrValidateAddressRequestPincodeLengthValidation
		err.Value = t.Pincode
		errs = append(errs, err)
	}

	if !validationhelper.IsNumeric(t.Pincode) {
		err := ErrValidateAddressRequestPincodeNumericValidation
		err.Value = t.Pincode
		errs = append(errs, err)
	}

	if t.Pincode == "" {
		err := ErrValidateAddressRequestPincodeRequiredValidation
		err.Value = t.Pincode
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ValidateAddressRequest)(nil)

func (t *ValidateAddressRequest) Validate() error {
	return ValidateValidateAddressRequest(t)
}
