// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetTimelineRequest is returned when the GetTimelineRequest is nil.
	ErrNilGetTimelineRequest = errors.New("input GetTimelineRequest is nil")

	// ErrGetTimelineRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrGetTimelineRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "GetTimelineRequest.RequestID", Type: "required"}

	// ErrGetTimelineRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrGetTimelineRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "GetTimelineRequest.RequestID", Type: "uuid"}
)

func ValidateGetTimelineRequest(t *GetTimelineRequest) error {
	if t == nil {
		return ErrNilGetTimelineRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrGetTimelineRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrGetTimelineRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetTimelineRequest)(nil)

func (t *GetTimelineRequest) Validate() error {
	return ValidateGetTimelineRequest(t)
}
