// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilGetRequestDocumentsRequest is returned when the GetRequestDocumentsRequest is nil.
	ErrNilGetRequestDocumentsRequest = errors.New("input GetRequestDocumentsRequest is nil")

	// ErrGetRequestDocumentsRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrGetRequestDocumentsRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "GetRequestDocumentsRequest.RequestID", Type: "required"}

	// ErrGetRequestDocumentsRequestRequestIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrGetRequestDocumentsRequestRequestIDUUIDValidation = govaliderrors.ValidationError{Reason: "field RequestID must be a valid UUID", Path: "GetRequestDocumentsRequest.RequestID", Type: "uuid"}
)

func ValidateGetRequestDocumentsRequest(t *GetRequestDocumentsRequest) error {
	if t == nil {
		return ErrNilGetRequestDocumentsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrGetRequestDocumentsRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if !isValidUUID(t.RequestID) {
		err := ErrGetRequestDocumentsRequestRequestIDUUIDValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GetRequestDocumentsRequest)(nil)

func (t *GetRequestDocumentsRequest) Validate() error {
	return ValidateGetRequestDocumentsRequest(t)
}
