// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilListCustomerRequestsRequest is returned when the ListCustomerRequestsRequest is nil.
	ErrNilListCustomerRequestsRequest = errors.New("input ListCustomerRequestsRequest is nil")

	// ErrListCustomerRequestsRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrListCustomerRequestsRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "ListCustomerRequestsRequest.CustomerID", Type: "required"}

	// ErrListCustomerRequestsRequestCustomerIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrListCustomerRequestsRequestCustomerIDUUIDValidation = govaliderrors.ValidationError{Reason: "field CustomerID must be a valid UUID", Path: "ListCustomerRequestsRequest.CustomerID", Type: "uuid"}
)

func ValidateListCustomerRequestsRequest(t *ListCustomerRequestsRequest) error {
	if t == nil {
		return ErrNilListCustomerRequestsRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.CustomerID == "" {
		err := ErrListCustomerRequestsRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if !isValidUUID(t.CustomerID) {
		err := ErrListCustomerRequestsRequestCustomerIDUUIDValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ListCustomerRequestsRequest)(nil)

func (t *ListCustomerRequestsRequest) Validate() error {
	return ValidateListCustomerRequestsRequest(t)
}
