// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDuplicateCheckRequest is returned when the DuplicateCheckRequest is nil.
	ErrNilDuplicateCheckRequest = errors.New("input DuplicateCheckRequest is nil")

	// ErrDuplicateCheckRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrDuplicateCheckRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "DuplicateCheckRequest.CustomerID", Type: "required"}

	// ErrDuplicateCheckRequestCustomerIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrDuplicateCheckRequestCustomerIDUUIDValidation = govaliderrors.ValidationError{Reason: "field CustomerID must be a valid UUID", Path: "DuplicateCheckRequest.CustomerID", Type: "uuid"}

	// ErrDuplicateCheckRequestRequestTypeOneofValidation is the error returned when the field is not one of the allowed values.
	ErrDuplicateCheckRequestRequestTypeOneofValidation = govaliderrors.ValidationError{Reason: "field RequestType must be one of ADDRESS_CHANGE NAME_CHANGE", Path: "DuplicateCheckRequest.RequestType", Type: "oneof"}

	// ErrDuplicateCheckRequestRequestTypeRequiredValidation is returned when the RequestType is required but not provided.
	ErrDuplicateCheckRequestRequestTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestType is required", Path: "DuplicateCheckRequest.RequestType", Type: "required"}
)

func ValidateDuplicateCheckRequest(t *DuplicateCheckRequest) error {
	if t == nil {
		return ErrNilDuplicateCheckRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.CustomerID == "" {
		err := ErrDuplicateCheckRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if !isValidUUID(t.CustomerID) {
		err := ErrDuplicateCheckRequestCustomerIDUUIDValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if !(t.RequestType == "ADDRESS_CHANGE" || t.RequestType == "NAME_CHANGE") {
		err := ErrDuplicateCheckRequestRequestTypeOneofValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.RequestType == "" {
		err := ErrDuplicateCheckRequestRequestTypeRequiredValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DuplicateCheckRequest)(nil)

func (t *DuplicateCheckRequest) Validate() error {
	return ValidateDuplicateCheckRequest(t)
}
