// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilDownloadDocumentRequest is returned when the DownloadDocumentRequest is nil.
	ErrNilDownloadDocumentRequest = errors.New("input DownloadDocumentRequest is nil")

	// ErrDownloadDocumentRequestDocumentIDRequiredValidation is returned when the DocumentID is required but not provided.
	ErrDownloadDocumentRequestDocumentIDRequiredValidation = govaliderrors.ValidationError{Reason: "field DocumentID is required", Path: "DownloadDocumentRequest.DocumentID", Type: "required"}

	// ErrDownloadDocumentRequestDocumentIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrDownloadDocumentRequestDocumentIDUUIDValidation = govaliderrors.ValidationError{Reason: "field DocumentID must be a valid UUID", Path: "DownloadDocumentRequest.DocumentID", Type: "uuid"}
)

func ValidateDownloadDocumentRequest(t *DownloadDocumentRequest) error {
	if t == nil {
		return ErrNilDownloadDocumentRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.DocumentID == "" {
		err := ErrDownloadDocumentRequestDocumentIDRequiredValidation
		err.Value = t.DocumentID
		errs = append(errs, err)
	}

	if !isValidUUID(t.DocumentID) {
		err := ErrDownloadDocumentRequestDocumentIDUUIDValidation
		err.Value = t.DocumentID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*DownloadDocumentRequest)(nil)

func (t *DownloadDocumentRequest) Validate() error {
	return ValidateDownloadDocumentRequest(t)
}
